import {
  InventoryItem,
  BorrowingRecord,
  PoskoFacility,
  PoskoRoomLayout,
  EventSetup,
  TransportRecord,
  MaintenanceLog,
} from '../types';

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    code: 'PKB-ELE-001',
    name: 'Proyektor Epson EB-E500',
    category: 'Elektronik',
    quantity: 1,
    availableQty: 1,
    unit: 'Unit',
    condition: 'Bagus',
    ownership: 'Kampus',
    lenderName: 'Laboratorium FT Kampus',
    location: 'Box A - Rak Posko 1',
    notes: 'Kabel HDMI & VGA lengkap di tas proyektor',
  },
  {
    id: 'inv-2',
    code: 'PKB-ELE-002',
    name: 'Sound System Portable Wireless + 2 Mic',
    category: 'Elektronik',
    quantity: 1,
    availableQty: 0,
    unit: 'Set',
    condition: 'Bagus',
    ownership: 'Sewa',
    lenderName: 'Rental Sound Mas Joko (0812-3456-7890)',
    location: 'Dipakai di Balai Desa',
    notes: 'Baterai mic cadangan 4 buah A2',
  },
  {
    id: 'inv-3',
    code: 'PKB-ELE-003',
    name: 'Kabel Roll 25 Meter Heavy Duty',
    category: 'Elektronik',
    quantity: 3,
    availableQty: 2,
    unit: 'Roll',
    condition: 'Bagus',
    ownership: 'Kelompok',
    location: 'Rak Posko 1',
    notes: '1 Roll stopkontak 4 lubang',
  },
  {
    id: 'inv-4',
    code: 'PKB-PRK-001',
    name: 'Toolkit Set (Palu, Tang, Obeng, Gergaji)',
    category: 'Perkakas',
    quantity: 1,
    availableQty: 1,
    unit: 'Box',
    condition: 'Bagus',
    ownership: 'Kelompok',
    location: 'Gudang Logistik Posko',
    notes: 'Lengkap dengan paku kayu dan fischer',
  },
  {
    id: 'inv-5',
    code: 'PKB-DPR-001',
    name: 'Kompor Gas Rinnai 2 Tungku + Tabung 3kg',
    category: 'Dapur',
    quantity: 2,
    availableQty: 2,
    unit: 'Set',
    condition: 'Bagus',
    ownership: 'Warga Desa',
    lenderName: 'Bu RT 02 (Ibu Sumi)',
    location: 'Dapur Posko KKN',
    notes: 'Regulator aman, cadangan tabung 1 buah',
  },
  {
    id: 'inv-6',
    code: 'PKB-ACR-001',
    name: 'Spanduk Utama Perpisahan KKN 3x1m',
    category: 'Acara',
    quantity: 2,
    availableQty: 2,
    unit: 'Pcs',
    condition: 'Bagus',
    ownership: 'Kelompok',
    location: 'Rak Bening Posko',
    notes: 'Sudah di-cincin 4 sudut untuk tali',
  },
  {
    id: 'inv-7',
    code: 'PKB-AKM-001',
    name: 'Dispenser Air Hot & Normal Miyako',
    category: 'Akomodasi',
    quantity: 1,
    availableQty: 1,
    unit: 'Unit',
    condition: 'Bagus',
    ownership: 'Kelompok',
    location: 'Ruang Tengah Posko',
    notes: 'Pembersihan galon tiap 2 hari',
  },
  {
    id: 'inv-8',
    code: 'PKB-ACR-002',
    name: 'Terpal Plastik Biru 4x6 Meter',
    category: 'Acara',
    quantity: 2,
    availableQty: 1,
    unit: 'Lembar',
    condition: 'Bagus',
    ownership: 'Warga Desa',
    lenderName: 'Pak Kadus 01',
    location: 'Halaman Belakang Posko',
    notes: 'Untuk alas panggung / perpisahan',
  },
];

export const INITIAL_BORROWINGS: BorrowingRecord[] = [
  {
    id: 'bor-1',
    itemName: 'Sound System Portable Wireless',
    inventoryId: 'inv-2',
    lenderName: 'Mas Joko Rental Sound',
    lenderPhone: '0812-3456-7890',
    borrowerName: 'Andi (PJ Perkab)',
    borrowDate: '2026-07-20',
    dueDate: '2026-07-25',
    quantity: 1,
    depositCost: 150000,
    status: 'Dipinjam',
    notes: 'Untuk acara Sosialisasi Stunting di Balai Desa',
  },
  {
    id: 'bor-2',
    itemName: 'Kursi Plastik Napolly 50 Biji',
    lenderName: 'Balai Desa Suka Maju (Pak Carik)',
    lenderPhone: '0857-1122-3344',
    borrowerName: 'Budi (Perkab Logistik)',
    borrowDate: '2026-07-18',
    dueDate: '2026-07-24',
    quantity: 50,
    depositCost: 0,
    status: 'Dipinjam',
    notes: 'Harus dipulangkan dalam kondisi bersih',
  },
  {
    id: 'bor-3',
    itemName: 'Tikar Matras Pandan 5 Lembar',
    lenderName: 'Mbah Tarjo (Warga RT 01)',
    lenderPhone: '0813-9988-7766',
    borrowerName: 'Siti (Sekretaris KKN)',
    borrowDate: '2026-07-10',
    dueDate: '2026-07-17',
    returnDate: '2026-07-17',
    quantity: 5,
    depositCost: 0,
    status: 'Dikembalikan',
    conditionOnReturn: 'Bagus',
    notes: 'Sudah dijemur dan dikembalikan tepat waktu',
  },
  {
    id: 'bor-4',
    itemName: 'Proyektor Epson EB-E500',
    inventoryId: 'inv-1',
    lenderName: 'Laboratorium FT Kampus',
    lenderPhone: '0274-555-1234',
    borrowerName: 'Andi (PJ Perkab)',
    borrowDate: '2026-07-01',
    dueDate: '2026-08-10',
    quantity: 1,
    depositCost: 0,
    status: 'Dipinjam',
    notes: 'Pinjaman dinas selama periode KKN',
  },
];

export const INITIAL_POSKO_FACILITIES: PoskoFacility[] = [
  {
    id: 'pos-1',
    facilityName: 'Daya Listrik Posko (1300 Watt)',
    category: 'Listrik',
    status: 'Sangat Baik',
    details: 'Pulsa token sisa 145 kWh. Pembagian stopkontak teratur tanpa overload.',
    lastChecked: '2026-07-22',
    picName: 'Andi',
  },
  {
    id: 'pos-2',
    facilityName: 'Air Clean & Sumur Pompa',
    category: 'Air',
    status: 'Sangat Baik',
    details: 'Debit air jernih, filter air dibersihkan tiap minggu. Tandon penuh.',
    lastChecked: '2026-07-23',
    picName: 'Budi',
  },
  {
    id: 'pos-3',
    facilityName: 'Kamar Tidur Putra & Matras',
    category: 'Kamar Tidur',
    status: 'Sangat Baik',
    details: 'Kapasitas 6 orang. 4 matras busa + 2 sleeping bag.',
    lastChecked: '2026-07-21',
    picName: 'Rian',
  },
  {
    id: 'pos-4',
    facilityName: 'Kamar Tidur Putri & Ventilasi',
    category: 'Kamar Tidur',
    status: 'Sangat Baik',
    details: 'Kapasitas 8 orang. Kasur springbed & kipas angin bekerja normal.',
    lastChecked: '2026-07-21',
    picName: 'Siti',
  },
  {
    id: 'pos-5',
    facilityName: 'Kompor & Perlengkapan Dapur',
    category: 'Dapur',
    status: 'Perlu Perhatian',
    details: 'Tungku sebelah kiri agak kotor, perlu pembersihan nozzle gas.',
    lastChecked: '2026-07-22',
    picName: 'Maya',
  },
  {
    id: 'pos-6',
    facilityName: 'Sanitasi Kamar Mandi Posko',
    category: 'Sanitasi',
    status: 'Sangat Baik',
    details: 'Kloset & pembuangan lancar. Stok sabun & pembersih cukup.',
    lastChecked: '2026-07-23',
    picName: 'Budi',
  },
];

export const INITIAL_ROOM_LAYOUTS: PoskoRoomLayout[] = [
  {
    id: 'room-1',
    roomName: 'Kamar Depan (Putra)',
    capacity: 6,
    occupants: ['Andi (KORDEK)', 'Budi (Perkab)', 'Rian (PDD)', 'Faris (Humas)', 'Dimas (Koor)', 'Reza (Bara)'],
    assignedEquipment: ['1 Kipas Angin Stand', '1 Kabel Roll 4 Lubang', '6 Sleeping Bag/Matras'],
    notes: 'Ruang depan samping teras, digunakan juga untuk simpan toolkit',
  },
  {
    id: 'room-2',
    roomName: 'Kamar Tengah (Putri)',
    capacity: 8,
    occupants: ['Siti (Sekretaris)', 'Maya (Bendahara)', 'Lia (Acara)', 'Nisa (Konsumsi)', 'Rina (Logistik)', 'Dewi (Kesehatan)', 'Tia (Konsumsi)', 'Eka (PDD)'],
    assignedEquipment: ['1 Kipas Angin Dinding', '2 Extension Socket', '2 Kasur Busa Besar'],
    notes: 'Kamar utama lantai 1',
  },
  {
    id: 'room-3',
    roomName: 'Ruang Rapat & Storage Perkab',
    capacity: 0,
    occupants: [],
    assignedEquipment: ['Rak Besi Logistik 3 Tingkat', 'Box A Proyektor', 'Box B Kabel', 'Papan Whiteboard Proker'],
    notes: 'Pusat komando logistik dan tempat briefing harian',
  },
];

export const INITIAL_EVENT_SETUPS: EventSetup[] = [
  {
    id: 'evt-1',
    eventName: 'Sosialisasi Pencegahan Stunting & Gizi Anak',
    eventDate: '2026-07-24 09:00',
    location: 'Balai Desa Suka Maju',
    picName: 'Andi (PJ Perkab)',
    setupStatus: 'Terangkut',
    requiredItems: [
      { id: 'c1', itemName: 'Proyektor & Layar Screen', qty: 1, isReady: true },
      { id: 'c2', itemName: 'Sound System & Mic Wireless', qty: 1, isReady: true },
      { id: 'c3', itemName: 'Kursi Peserta (Napolly)', qty: 50, isReady: true },
      { id: 'c4', itemName: 'Kabel Roll Extension 25m', qty: 2, isReady: true },
      { id: 'c5', itemName: 'Spanduk Banner Acara 3x1m', qty: 1, isReady: false },
    ],
    notes: 'Check-in lokasi jam 07:30 WIB. Pemasangan banner dan uji coba mic.',
  },
  {
    id: 'evt-2',
    eventName: 'Perpisahan KKN & Pentas Seni Pemuda Desa',
    eventDate: '2026-08-05 19:00',
    location: 'Lapangan Olahraga Desa',
    picName: 'Budi (Perkab)',
    setupStatus: 'Perencanaan',
    requiredItems: [
      { id: 'c6', itemName: 'Panggung Portable / Modul Wood', qty: 1, isReady: false },
      { id: 'c7', itemName: 'Sound System High Watt + 4 Mic', qty: 1, isReady: false },
      { id: 'c8', itemName: 'Lampu Lighting LED & Kabel Power', qty: 4, isReady: false },
      { id: 'c9', itemName: 'Terpal Alas Penonton 4x6', qty: 3, isReady: true },
      { id: 'c10', itemName: 'Genset Backup 3000W', qty: 1, isReady: false },
    ],
    notes: 'Memerlukan kendaraan Pick-up untuk angkut panggung dari RT 03.',
  },
];

export const INITIAL_TRANSPORTS: TransportRecord[] = [
  {
    id: 'trp-1',
    vehicleName: 'Pick-up Grand Max (Pak Eko)',
    vehicleType: 'Pick-up',
    driverName: 'Pak Eko (Warga)',
    purpose: 'Angkut Peralatan Sound & Kursi ke Balai Desa',
    departureDate: '2026-07-24 07:00',
    returnDate: '2026-07-24 13:00',
    cargoDetails: '1 Set Sound System, 50 Kursi Plastik, 2 Terpal',
    cost: 75000,
    status: 'Jadwal',
  },
  {
    id: 'trp-2',
    vehicleName: 'Motor Vario AB 4567 XY',
    vehicleType: 'Motor',
    driverName: 'Rian (PDD)',
    purpose: 'Belanja Bahan Cetak Spanduk & ATK di Kota',
    departureDate: '2026-07-23 10:00',
    returnDate: '2026-07-23 12:30',
    cargoDetails: 'Buku Tamu, Spanduk Stunting, Pita & Sertifikat',
    cost: 25000,
    status: 'Selesai',
  },
];

export const INITIAL_MAINTENANCE_LOGS: MaintenanceLog[] = [
  {
    id: 'mt-1',
    itemName: 'Kabel Roll Stopkontak Lubang 3',
    reportedBy: 'Rian (PDD)',
    damageDescription: 'Kabel agak terkelupas di dekat colokan steker karena tertarik.',
    estimatedCost: 15000,
    status: 'Selesai Perbaikan',
    resolutionNotes: 'Sudah dilapisi solasi ban listrik hitam tebal & di-test multimeter aman.',
    dateReported: '2026-07-15',
  },
  {
    id: 'mt-2',
    itemName: 'Mic Wireless 2 (Merah)',
    reportedBy: 'Budi (Perkab)',
    damageDescription: 'Suara kadang kretek-kretek jika tombol switch digeser.',
    estimatedCost: 35000,
    status: 'Dalam Perbaikan',
    resolutionNotes: 'Dibawa ke tukang servis elektronik desa oleh Pak RT.',
    dateReported: '2026-07-21',
  },
];
